// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameAttestation = "attestations"

// Attestation mapped from table <attestations>
type Attestation struct {
	SlotNumber      int64     `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	Index           int32     `gorm:"column:index;primaryKey" json:"index"`
	BeaconBlockRoot string    `gorm:"column:beacon_block_root" json:"beacon_block_root"`
	AggregationBits string    `gorm:"column:aggregation_bits" json:"aggregation_bits"`
	AttestationSlot int64     `gorm:"column:attestation_slot" json:"attestation_slot"`
	SourceEpoch     int64     `gorm:"column:source_epoch" json:"source_epoch"`
	SourceRoot      string    `gorm:"column:source_root" json:"source_root"`
	TargetEpoch     int64     `gorm:"column:target_epoch" json:"target_epoch"`
	TargetRoot      string    `gorm:"column:target_root" json:"target_root"`
	Signature       string    `gorm:"column:signature;primaryKey" json:"signature"`
	BlockTime       time.Time `gorm:"column:block_time;not null;type:timestamp" json:"block_time"`
	BlockNumber     int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash       string    `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate       time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Attestation's table name
func (*Attestation) TableName() string {
	return TableNameAttestation
}
