// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"

	"github.com/lib/pq"
)

const TableNameAttesterSlashing = "attester_slashings"

// AttesterSlashing mapped from table <attester_slashings>
type AttesterSlashing struct {
	SlotNumber                   int64          `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	Index                        int32          `gorm:"column:index;primaryKey" json:"index"`
	Attestation1AttestingIndices pq.StringArray `gorm:"column:attestation_1_attesting_indices;type:text[]" json:"attestation_1_attesting_indices"`
	Attestation1Slot             int64          `gorm:"column:attestation_1_slot" json:"attestation_1_slot"`
	Attestation1Index            int32          `gorm:"column:attestation_1_index" json:"attestation_1_index"`
	Attestation1BeaconBlockRoot  string         `gorm:"column:attestation_1_beacon_block_root" json:"attestation_1_beacon_block_root"`
	Attestation1SourceEpoch      int64          `gorm:"column:attestation_1_source_epoch" json:"attestation_1_source_epoch"`
	Attestation1SourceRoot       string         `gorm:"column:attestation_1_source_root" json:"attestation_1_source_root"`
	Attestation1TargetEpoch      int64          `gorm:"column:attestation_1_target_epoch" json:"attestation_1_target_epoch"`
	Attestation1TargetRoot       string         `gorm:"column:attestation_1_target_root" json:"attestation_1_target_root"`
	Attestation1Signature        string         `gorm:"column:attestation_1_signature" json:"attestation_1_signature"`
	Attestation2AttestingIndices pq.StringArray `gorm:"column:attestation_2_attesting_indices;type:text[]" json:"attestation_2_attesting_indices"`
	Attestation2Slot             int64          `gorm:"column:attestation_2_slot" json:"attestation_2_slot"`
	Attestation2Index            int32          `gorm:"column:attestation_2_index" json:"attestation_2_index"`
	Attestation2BeaconBlockRoot  string         `gorm:"column:attestation_2_beacon_block_root" json:"attestation_2_beacon_block_root"`
	Attestation2SourceEpoch      int64          `gorm:"column:attestation_2_source_epoch" json:"attestation_2_source_epoch"`
	Attestation2SourceRoot       string         `gorm:"column:attestation_2_source_root" json:"attestation_2_source_root"`
	Attestation2TargetEpoch      int64          `gorm:"column:attestation_2_target_epoch" json:"attestation_2_target_epoch"`
	Attestation2TargetRoot       string         `gorm:"column:attestation_2_target_root" json:"attestation_2_target_root"`
	Attestation2Signature        string         `gorm:"column:attestation_2_signature" json:"attestation_2_signature"`
	BlockTime                    time.Time      `gorm:"column:block_time;not null;type:timestamp" json:"block_time"`
	BlockNumber                  int64          `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash                    string         `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate                    time.Time      `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName AttesterSlashing's table name
func (*AttesterSlashing) TableName() string {
	return TableNameAttesterSlashing
}
