// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameBlob = "blobs"

// Blob mapped from table <blobs>
type Blob struct {
	SlotNumber                  int64     `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	ProposerIndex               int64     `gorm:"column:proposer_index;not null" json:"proposer_index"`
	ParentRoot                  string    `gorm:"column:parent_root;not null" json:"parent_root"`
	StateRoot                   string    `gorm:"column:state_root;not null" json:"state_root"`
	BodyRoot                    string    `gorm:"column:body_root;not null" json:"body_root"`
	Signature                   string    `gorm:"column:signature;primaryKey" json:"signature"`
	KzgCommitment               string    `gorm:"column:kzg_commitment;not null" json:"kzg_commitment"`
	KzgProof                    string    `gorm:"column:kzg_proof;not null" json:"kzg_proof"`
	KzgCommitmentInclusionProof string    `gorm:"column:kzg_commitment_inclusion_proof;not null" json:"kzg_commitment_inclusion_proof"`
	Index                       int64     `gorm:"column:index;primaryKey" json:"index"`
	Blob                        string    `gorm:"column:blob;not null" json:"blob"`
	BlockTime                   time.Time `gorm:"column:block_time;not null" json:"block_time"`
	BlockNumber                 int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash                   string    `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate                   time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Blob's table name
func (*Blob) TableName() string {
	return TableNameBlob
}
