// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameBlock = "blocks"

// Block mapped from table <blocks>
type Block struct {
	SlotNumber                 int64     `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	EpochNumber                int64     `gorm:"column:epoch_number;not null" json:"epoch_number"`
	ProposerIndex              int64     `gorm:"column:proposer_index;not null" json:"proposer_index"`
	ParentRoot                 string    `gorm:"column:parent_root;not null" json:"parent_root"`
	StateRoot                  string    `gorm:"column:state_root;not null" json:"state_root"`
	RandaoReveal               string    `gorm:"column:randao_reveal;not null" json:"randao_reveal"`
	Graffiti                   string    `gorm:"column:graffiti;not null" json:"graffiti"`
	Eth1BlockHash              string    `gorm:"column:eth1_block_hash;not null" json:"eth1_block_hash"`
	Eth1DepositRoot            string    `gorm:"column:eth1_deposit_root;not null" json:"eth1_deposit_root"`
	Eth1DepositCount           int64     `gorm:"column:eth1_deposit_count;not null" json:"eth1_deposit_count"`
	SyncCommitteeBits          string    `gorm:"column:sync_committee_bits" json:"sync_committee_bits"`
	SyncCommitteeSignature     string    `gorm:"column:sync_committee_signature" json:"sync_committee_signature"`
	ParentHash                 string    `gorm:"column:parent_hash;not null" json:"parent_hash"`
	BlockTime                  time.Time `gorm:"column:block_time;not null;type:timestamp" json:"block_time"`
	BlockNumber                int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash                  string    `gorm:"column:block_hash;not null" json:"block_hash"`
	AttestationsCount          int32     `gorm:"column:attestations_count;not null" json:"attestations_count"`
	DepositsCount              int32     `gorm:"column:deposits_count;not null" json:"deposits_count"`
	ProposerSlashingsCount     int32     `gorm:"column:proposer_slashings_count;not null" json:"proposer_slashings_count"`
	AttesterSlashingsCount     int32     `gorm:"column:attester_slashings_count;not null" json:"attester_slashings_count"`
	VoluntaryExitsCount        int32     `gorm:"column:voluntary_exits_count;not null" json:"voluntary_exits_count"`
	BlsToExecutionChangesCount int32     `gorm:"column:bls_to_execution_changes_count;not null" json:"bls_to_execution_changes_count"`
	WithdrawalsCount           int32     `gorm:"column:withdrawals_count;not null" json:"withdrawals_count"`
	Signature                  string    `gorm:"column:signature;not null" json:"signature"`
	Version                    string    `gorm:"column:version;not null" json:"version"`
	ExecutionOptimistic        bool      `gorm:"column:execution_optimistic;not null" json:"execution_optimistic"`
	Finalized                  bool      `gorm:"column:finalized;not null" json:"finalized"`
	BlockDate                  time.Time `gorm:"column:block_date;not null" json:"block_date"`
	BlockRoot                  string    `gorm:"column:block_root" json:"block_root"`
}

// TableName Block's table name
func (*Block) TableName() string {
	return TableNameBlock
}
