// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameBlsToExecutionChange = "bls_to_execution_changes"

// BlsToExecutionChange mapped from table <bls_to_execution_changes>
type BlsToExecutionChange struct {
	SlotNumber         int64     `gorm:"column:slot_number;not null" json:"slot_number"`
	Index              int32     `gorm:"column:index;not null" json:"index"`
	ValidatorIndex     int64     `gorm:"column:validator_index;primaryKey" json:"validator_index"`
	FromBlsPubkey      string    `gorm:"column:from_bls_pubkey" json:"from_bls_pubkey"`
	ToExecutionAddress string    `gorm:"column:to_execution_address" json:"to_execution_address"`
	Signature          string    `gorm:"column:signature" json:"signature"`
	BlockTime          time.Time `gorm:"column:block_time;not null" json:"block_time"`
	BlockNumber        int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash          string    `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate          time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName BlsToExecutionChange's table name
func (*BlsToExecutionChange) TableName() string {
	return TableNameBlsToExecutionChange
}
