// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

const TableNameValidator = "validators"

// Validator mapped from table <validators>
type Validator struct {
	Index                      int64   `gorm:"column:index;primaryKey" json:"index"`
	Status                     string  `gorm:"column:status;not null" json:"status"`
	Balance                    float64 `gorm:"column:balance;not null" json:"balance"`
	ActivationEligibilityEpoch float64 `gorm:"column:activation_eligibility_epoch;not null" json:"activation_eligibility_epoch"`
	ActivationEpoch            float64 `gorm:"column:activation_epoch;not null" json:"activation_epoch"`
	EffectiveBalance           float64 `gorm:"column:effective_balance;not null" json:"effective_balance"`
	ExitEpoch                  float64 `gorm:"column:exit_epoch;not null" json:"exit_epoch"`
	Pubkey                     string  `gorm:"column:pubkey;primaryKey" json:"pubkey"`
	Slashed                    bool    `gorm:"column:slashed;not null" json:"slashed"`
	WithdrawableEpoch          float64 `gorm:"column:withdrawable_epoch;not null" json:"withdrawable_epoch"`
	WithdrawalCredentials      string  `gorm:"column:withdrawal_credentials;not null" json:"withdrawal_credentials"`
}

// TableName Validator's table name
func (*Validator) TableName() string {
	return TableNameValidator
}
