// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameVoluntaryExit = "voluntary_exits"

// VoluntaryExit mapped from table <voluntary_exits>
type VoluntaryExit struct {
	SlotNumber     int64     `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	Index          int32     `gorm:"column:index;primaryKey" json:"index"`
	EpochNumber    int64     `gorm:"column:epoch_number;not null" json:"epoch_number"`
	ValidatorIndex int64     `gorm:"column:validator_index" json:"validator_index"`
	Signature      string    `gorm:"column:signature" json:"signature"`
	BlockTime      time.Time `gorm:"column:block_time;not null;type:timestamp" json:"block_time"`
	BlockNumber    int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash      string    `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate      time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName VoluntaryExit's table name
func (*VoluntaryExit) TableName() string {
	return TableNameVoluntaryExit
}
