// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package beacon

import (
	"time"
)

const TableNameWithdrawal = "withdrawals"

// Withdrawal mapped from table <withdrawals>
type Withdrawal struct {
	SlotNumber     int64     `gorm:"column:slot_number;primaryKey" json:"slot_number"`
	Index          int32     `gorm:"column:index;primaryKey" json:"index"`
	ValidatorIndex int64     `gorm:"column:validator_index;primaryKey" json:"validator_index"`
	Address        string    `gorm:"column:address" json:"address"`
	Amount         float64   `gorm:"column:amount" json:"amount"`
	BlockTime      time.Time `gorm:"column:block_time;not null" json:"block_time"`
	BlockNumber    int64     `gorm:"column:block_number;not null" json:"block_number"`
	BlockHash      string    `gorm:"column:block_hash;not null" json:"block_hash"`
	BlockDate      time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Withdrawal's table name
func (*Withdrawal) TableName() string {
	return TableNameWithdrawal
}
