// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	AccountID          string    `gorm:"column:account_id;primaryKey" json:"account_id"`
	PagingToken        string    `gorm:"column:paging_token;not null" json:"paging_token"`
	Sequence           string    `gorm:"column:sequence;not null" json:"sequence"`
	SequenceLedger     int64     `gorm:"column:sequence_ledger" json:"sequence_ledger"`
	SequenceTime       time.Time `gorm:"column:sequence_time" json:"sequence_time"`
	SubentryCount      int32     `gorm:"column:subentry_count" json:"subentry_count"`
	HomeDomain         string    `gorm:"column:home_domain" json:"home_domain"`
	LastModifiedLedger int64     `gorm:"column:last_modified_ledger" json:"last_modified_ledger"`
	LastModifiedTime   time.Time `gorm:"column:last_modified_time" json:"last_modified_time"`
	Sponsor            string    `gorm:"column:sponsor" json:"sponsor"`
	Thresholds         string    `gorm:"column:thresholds" json:"thresholds"`
	Flags              string    `gorm:"column:flags" json:"flags"`
	Balances           string    `gorm:"column:balances" json:"balances"`
	Signers            string    `gorm:"column:signers" json:"signers"`
	Data               string    `gorm:"column:data" json:"data"`
	NumSponsoring      int32     `gorm:"column:num_sponsoring" json:"num_sponsoring"`
	NumSponsored       int32     `gorm:"column:num_sponsored" json:"num_sponsored"`
	ProcessTime        time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate          time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
