// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameContractDatum = "contract_data"

// ContractDatum mapped from table <contract_data>
type ContractDatum struct {
	LedgerKeyHash      string    `gorm:"column:ledger_key_hash" json:"ledger_key_hash"`
	ContractID         string    `gorm:"column:contract_id" json:"contract_id"`
	ContractKeyType    string    `gorm:"column:contract_key_type" json:"contract_key_type"`
	Durability         string    `gorm:"column:durability" json:"durability"`
	AssetCode          string    `gorm:"column:asset_code" json:"asset_code"`
	AssetIssuer        string    `gorm:"column:asset_issuer" json:"asset_issuer"`
	AssetType          string    `gorm:"column:asset_type" json:"asset_type"`
	BalanceHolder      string    `gorm:"column:balance_holder" json:"balance_holder"`
	BalanceAmount      float64   `gorm:"column:balance_amount" json:"balance_amount"`
	LastModifiedLedger int64     `gorm:"column:last_modified_ledger" json:"last_modified_ledger"`
	ProcessTime        time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate          time.Time `gorm:"column:block_date" json:"block_date"`
}

// TableName ContractDatum's table name
func (*ContractDatum) TableName() string {
	return TableNameContractDatum
}
