// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameContract = "contracts"

// Contract mapped from table <contracts>
type Contract struct {
	ContractID      string    `gorm:"column:contract_id;primaryKey" json:"contract_id"`
	ContractKeyType string    `gorm:"column:contract_key_type" json:"contract_key_type"`
	Durability      string    `gorm:"column:durability" json:"durability"`
	AssetCode       string    `gorm:"column:asset_code" json:"asset_code"`
	AssetIssuer     string    `gorm:"column:asset_issuer" json:"asset_issuer"`
	AssetType       string    `gorm:"column:asset_type" json:"asset_type"`
	ProcessTime     time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate       time.Time `gorm:"column:block_date" json:"block_date"`
	LedgerKeyHash   string    `gorm:"column:ledger_key_hash" json:"ledger_key_hash"`
}

// TableName Contract's table name
func (*Contract) TableName() string {
	return TableNameContract
}
