// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID                       string    `gorm:"column:id;primaryKey" json:"id"`
	PagingToken              string    `gorm:"column:paging_token" json:"paging_token"`
	Type                     string    `gorm:"column:type" json:"type"`
	ContractID               string    `gorm:"column:contract_id" json:"contract_id"`
	Ledger                   int64     `gorm:"column:ledger" json:"ledger"`
	LedgerClosedAt           time.Time `gorm:"column:ledger_closed_at" json:"ledger_closed_at"`
	Topic                    string    `gorm:"column:topic" json:"topic"`
	TopicRaw                 string    `gorm:"column:topic_raw" json:"topic_raw"`
	Value                    string    `gorm:"column:value" json:"value"`
	ValueRaw                 string    `gorm:"column:value_raw" json:"value_raw"`
	TransactionHash          string    `gorm:"column:transaction_hash" json:"transaction_hash"`
	InSuccessfulContractCall bool      `gorm:"column:in_successful_contract_call" json:"in_successful_contract_call"`
	ProcessTime              time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate                time.Time `gorm:"column:block_date" json:"block_date"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
