// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameHistoryTransaction = "history_transactions"

// HistoryTransaction mapped from table <history_transactions>
type HistoryTransaction struct {
	ID                    string    `gorm:"column:id;primaryKey" json:"id"`
	PagingToken           string    `gorm:"column:paging_token;not null" json:"paging_token"`
	Hash                  string    `gorm:"column:hash;not null" json:"hash"`
	Successful            bool      `gorm:"column:successful;not null" json:"successful"`
	LedgerNumber          int64     `gorm:"column:ledger_number;not null" json:"ledger_number"`
	CreatedAt             time.Time `gorm:"column:created_at;not null" json:"created_at"`
	SourceAccount         string    `gorm:"column:source_account;not null" json:"source_account"`
	SourceAccountSequence int64     `gorm:"column:source_account_sequence;not null" json:"source_account_sequence"`
	FeeAccount            string    `gorm:"column:fee_account" json:"fee_account"`
	FeeCharged            float64   `gorm:"column:fee_charged" json:"fee_charged"`
	MaxFee                float64   `gorm:"column:max_fee" json:"max_fee"`
	OperationCount        int32     `gorm:"column:operation_count" json:"operation_count"`
	EnvelopeXdr           string    `gorm:"column:envelope_xdr" json:"envelope_xdr"`
	ResultXdr             string    `gorm:"column:result_xdr" json:"result_xdr"`
	ResultMetaXdr         string    `gorm:"column:result_meta_xdr" json:"result_meta_xdr"`
	FeeMetaXdr            string    `gorm:"column:fee_meta_xdr" json:"fee_meta_xdr"`
	Memo                  string    `gorm:"column:memo" json:"memo"`
	MemoType              string    `gorm:"column:memo_type" json:"memo_type"`
	Signatures            string    `gorm:"column:signatures" json:"signatures"`
	ValidBefore           string    `gorm:"column:valid_before" json:"valid_before"`
	ValidAfter            string    `gorm:"column:valid_after" json:"valid_after"`
	Preconditions         string    `gorm:"column:preconditions" json:"preconditions"`
	ProcessTime           time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate             time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName HistoryTransaction's table name
func (*HistoryTransaction) TableName() string {
	return TableNameHistoryTransaction
}
