// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameHistoryOperation = "history_operations"

// HistoryOperation mapped from table <history_operations>
type HistoryOperation struct {
	ID                    string    `gorm:"column:id;primaryKey" json:"id"`
	PagingToken           string    `gorm:"column:paging_token;not null" json:"paging_token"`
	Type                  string    `gorm:"column:type;not null" json:"type"`
	TypeI                 int32     `gorm:"column:type_i;not null" json:"type_i"`
	TransactionHash       string    `gorm:"column:transaction_hash;not null" json:"transaction_hash"`
	TransactionSuccessful bool      `gorm:"column:transaction_successful;not null" json:"transaction_successful"`
	SourceAccount         string    `gorm:"column:source_account;not null" json:"source_account"`
	CreatedAt             time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Details               string    `gorm:"column:details" json:"details"`
	LedgerNumber          int64     `gorm:"column:ledger_number;not null" json:"ledger_number"`
	ProcessTime           time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate             time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName HistoryOperation's table name
func (*HistoryOperation) TableName() string {
	return TableNameHistoryOperation
}
