// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameLiquidityPool = "liquidity_pools"

// LiquidityPool mapped from table <liquidity_pools>
type LiquidityPool struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	PagingToken        string    `gorm:"column:paging_token;not null" json:"paging_token"`
	FeeBp              int32     `gorm:"column:fee_bp" json:"fee_bp"`
	Type               string    `gorm:"column:type" json:"type"`
	TotalTrustlines    int32     `gorm:"column:total_trustlines" json:"total_trustlines"`
	LastModifiedLedger int64     `gorm:"column:last_modified_ledger" json:"last_modified_ledger"`
	LastModifiedTime   time.Time `gorm:"column:last_modified_time" json:"last_modified_time"`
	TotalShares        float64   `gorm:"column:total_shares" json:"total_shares"`
	Reserves           string    `gorm:"column:reserves" json:"reserves"`
	ProcessTime        time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate          time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName LiquidityPool's table name
func (*LiquidityPool) TableName() string {
	return TableNameLiquidityPool
}
