// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameOffer = "offers"

// Offer mapped from table <offers>
type Offer struct {
	ID                 int64     `gorm:"column:id;primaryKey" json:"id"`
	PagingToken        string    `gorm:"column:paging_token;not null" json:"paging_token"`
	Seller             string    `gorm:"column:seller;not null" json:"seller"`
	Selling            string    `gorm:"column:selling" json:"selling"`
	Buying             string    `gorm:"column:buying" json:"buying"`
	Amount             float64   `gorm:"column:amount" json:"amount"`
	PriceR             string    `gorm:"column:price_r" json:"price_r"`
	Price              float64   `gorm:"column:price" json:"price"`
	LastModifiedLedger int64     `gorm:"column:last_modified_ledger" json:"last_modified_ledger"`
	LastModifiedTime   time.Time `gorm:"column:last_modified_time" json:"last_modified_time"`
	Sponsor            string    `gorm:"column:sponsor" json:"sponsor"`
	ProcessTime        time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate          time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Offer's table name
func (*Offer) TableName() string {
	return TableNameOffer
}
