// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stellar

import (
	"time"
)

const TableNameTrade = "trades"

// Trade mapped from table <trades>
type Trade struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	PagingToken        string    `gorm:"column:paging_token;not null" json:"paging_token"`
	OperationID        int64     `gorm:"column:operation_id;not null" json:"operation_id"`
	Sequence           int32     `gorm:"column:sequence;not null" json:"sequence"`
	LedgerCloseTime    time.Time `gorm:"column:ledger_close_time;not null" json:"ledger_close_time"`
	TradeType          string    `gorm:"column:trade_type" json:"trade_type"`
	BaseAccount        string    `gorm:"column:base_account" json:"base_account"`
	BaseOfferID        int64     `gorm:"column:base_offer_id" json:"base_offer_id"`
	BaseAmount         float64   `gorm:"column:base_amount" json:"base_amount"`
	BaseAssetType      string    `gorm:"column:base_asset_type" json:"base_asset_type"`
	CounterAccount     string    `gorm:"column:counter_account" json:"counter_account"`
	CounterOfferID     int64     `gorm:"column:counter_offer_id" json:"counter_offer_id"`
	CounterAmount      float64   `gorm:"column:counter_amount" json:"counter_amount"`
	CounterAssetType   string    `gorm:"column:counter_asset_type" json:"counter_asset_type"`
	CounterAssetCode   string    `gorm:"column:counter_asset_code" json:"counter_asset_code"`
	CounterAssetIssuer string    `gorm:"column:counter_asset_issuer" json:"counter_asset_issuer"`
	BaseIsSeller       bool      `gorm:"column:base_is_seller" json:"base_is_seller"`
	Price              string    `gorm:"column:price" json:"price"`
	ProcessTime        time.Time `gorm:"column:process_time" json:"process_time"`
	BlockDate          time.Time `gorm:"column:block_date;not null" json:"block_date"`
}

// TableName Trade's table name
func (*Trade) TableName() string {
	return TableNameTrade
}
